import type { NextPage } from 'next'
import Head from 'next/head'
import { useAccount, useConnect, useDisconnect, useEnsAddress } from 'wagmi'
import styles from '../styles/Home.module.css'

const ConnectButton = () => {
  const { connect, connectors, isLoading } = useConnect();
  const connector = connectors[0];
  return <button onClick={() => connect({ connector })} disabled={isLoading}>Connect</button>;
}

const DisconnectButton = () => {
  const { disconnect, isLoading } = useDisconnect();
  return <button onClick={() => disconnect()} disabled={isLoading}>Disconnect</button>;
}

const MyAddress = () => {
  const { data: address, isLoading } = useEnsAddress({ name: 'ajmay.eth' });
  return <p>ajmay.eth: {isLoading ? 'loading...' : address}</p>;
}

const Home: NextPage = () => {
  const { isConnected, address } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>Wagmi SSR Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Wagmi SSR Test
        </h1>

        {isConnected ? <DisconnectButton /> : <ConnectButton />}

        <p>Address: {address ? address : 'Not connected'}</p>
        <MyAddress />
      </main>
    </div>
  )
}

export default Home
